#ifndef AEON_STREAMS_CONFIG_H__
#define AEON_STREAMS_CONFIG_H__

#define AEON_STREAMS_ENABLE_DEBUG_OUTPUT
#define AEON_STREAMS_DEBUG_OUTPUT_DESTINATION	stdout

#define AEON_STREAMS_MAX_TEXT_LINE_LENGTH		2048
#define AEON_STREAMS_DEFAULT_STREAM_NAME		"Stream"


//#define AEON_USE_AEON_CONSOLE_LIBRARY

#endif /* AEON_STREAMS_CONFIG_H__ */

